+ jpg
VeronikaVaraksina1/command-project-vyshyvanka-vibes pull request #2
Opened 2023-09-30 17:33 UTC by GudvinPRO

2023-09-30 20:35 UTC, VeronikaVaraksina1 commented on src/css/testimonials.css
> +    line-height: 1.45; /* 145.455% */
Коментарі, що вказуються в макеті фігми, потрібно прибирати з коду

2023-09-30 20:35 UTC, VeronikaVaraksina1 commented on src/css/testimonials.css
> +    color: var(--primary-text-color);
Прописувати color не потрібно, бо колір наслідується із глобальних стилів body, що вказані у файлі styles.css

2023-09-30 20:35 UTC, VeronikaVaraksina1 commented on src/css/testimonials.css
> +}
Не потрібно вказувати у вашому css файлі list-style: none; бо стандартні стилі списків вже скинуті у файлі reset.css

2023-09-30 20:35 UTC, VeronikaVaraksina1 commented on src/css/testimonials.css
> +}
Вираховувати ширину карток потрібно через calc, як ми це робили в домашці: width: calc((100% - 26px) / 3); (прописуємо в .staff-block)

2023-09-30 20:35 UTC, VeronikaVaraksina1 commented on src/css/testimonials.css
> +}
Списку прописуємо gap: 26px; щоб картки в li стали 396px в ширину (див. коментар до ваших li з класом .staff-block, там має бути ширина вирахувана через calc).

2023-09-30 20:35 UTC, VeronikaVaraksina1 commented on src/css/testimonials.css
> +}
Стилі для десктопу 1440px потрібно помістити в медіаправило @media screen and (min-width: 1440px), приберіть max-width, бо в глобальних стилях контейнеру (common.css) вже вказана ширина, вона наслідується. Поверніть діву, що вкладений в секцію, назву класу .container. Також ми починаємо писати стилі з ширини 320px, тобто вони і будуть базовими. Перша точка перелому у нас 375px, тобто потрібен медіазапит @media screen and (min-width: 375px), де ви будете перебивати базові стилі для розміру 320px. Наступна точка перелому для планшетів - @media screen and (min-width: 768px). Далі для десктопу - @media screen and (min-width: 1280px) і @media screen and (min-width: 1440px)

2023-09-30 20:35 UTC, VeronikaVaraksina1 commented on src/css/testimonials.css
> +    font-family: Manrope;
Приберіть font-family, він наслідується з глобальних стилів

2023-09-30 20:35 UTC, VeronikaVaraksina1 commented on src/css/testimonials.css
> +}
Приберіть ширину і пропишіть падінги за макетом, щоб здвинути контент від країв картки (по 18px праворуч, знизу, ліворуч). В h3 у Вас відсутній марджин між h3 та p, пропишіть марджин, що вказаний в макеті (8px), в клас .staff-title.

2023-10-01 05:07 UTC, GudvinPRO commented on src/partials/testimonials.html
> +            <img src="../img/testimonials/maria.jpg" srcset="../img/testimonials/maria@2.jpg" width="64" alt="Maria">
Добре. Зараз все перероблю

2023-10-01 08:59 UTC, VeronikaVaraksina1 requested changes
Потрібні зміни

2023-10-01 21:12 UTC, VeronikaVaraksina1 requested changes

2023-10-01 21:12 UTC, VeronikaVaraksina1 commented on src/css/testimonials.css
> +    padding-top: 80px;
Виправити на padding-bottom: 80px; щоб забезпечити правильний відступ від вашої секції до футеру

2023-10-01 21:12 UTC, VeronikaVaraksina1 commented on src/css/testimonials.css
> +        padding-top: 100px;
Виправити на padding-bottom: 100px; щоб забезпечити правильний відступ від вашої секції до футеру

2023-10-01 21:12 UTC, VeronikaVaraksina1 commented on src/css/testimonials.css
> +        padding-top: 150px;
Виправити на padding-bottom: 150px; щоб забезпечити правильний відступ від вашої секції до футеру

2023-10-01 21:12 UTC, VeronikaVaraksina1 commented on src/css/testimonials.css
> -.container_image {
Назви класів пишемо через дефіс, виправте на .container-image

2023-10-01 21:12 UTC, VeronikaVaraksina1 commented on src/css/testimonials.css
> +.testimonials_section{
Назви класів пишемо через дефіс, виправте на .testimonials-section

2023-10-01 21:12 UTC, VeronikaVaraksina1 commented on src/css/testimonials.css
>  .image_icon {
Назви класів пишемо через дефіс

2023-10-01 21:12 UTC, VeronikaVaraksina1 commented on src/css/testimonials.css
> +    .testimonials_section{
Назви класів пишемо через дефіс

2023-10-01 21:12 UTC, VeronikaVaraksina1 commented on src/css/testimonials.css
>      .testimonials-item {
В стилях h2 виправте кому на крапку в правилах, ось так щоб було:
line-height: 1.38;
letter-spacing: -0.03em;

В планшетних та десктопних стилях ви також неправильно вказали (має бути з мінусом), ось так треба: letter-spacing: -0.03em;

2023-10-01 21:12 UTC, VeronikaVaraksina1 commented on src/partials/testimonials.html
>                  <p class="staff-paragraph">
В стилях параграфу приберіть font-style: normal; він іде за замовчуванням з глобальних стилів

2023-10-01 21:12 UTC, VeronikaVaraksina1 commented on src/css/testimonials.css
>  .staff-title {
Приберіть зі стилів h3 font-style: normal; він йде за замовчуванням з глобальних стилів

2023-10-01 21:12 UTC, VeronikaVaraksina1 commented on src/partials/testimonials.html
>          <li class="staff-block">
В стилях .testimonials-staff на десктопі 1280px calc має бути width: calc((100% - 26px) / 3); (значення, що віднімається від 100% розміру батьківського елементу, має дорівнювати gap, що вказаний в .testimonials-staff, а саме 26px)

2023-10-01 21:12 UTC, VeronikaVaraksina1 commented on src/partials/testimonials.html
> +<section class="section testimonials_section">
Назву класів ми пишемо через дефіс, виправіть на testimonials-section

2023-10-01 21:12 UTC, VeronikaVaraksina1 commented on src/partials/testimonials.html
> +            <img class="image_icon" src="../img/testimonials/sergey.png" srcset="../img/testimonials/sergey@2.png" width="64" alt="Sergey">
Назву класу пишемо через дефіс

Не підтягується зображення для щільності пікселів DPR: 1.0
Ви забули вказати дескриптор 2x в атрибуті srcset. В слак надам Вам скріншот, як це має виглядати

2023-10-01 21:12 UTC, VeronikaVaraksina1 commented on src/partials/testimonials.html
> +            <img class="image_icon" src="../img/testimonials/natalia.png" srcset="../img/testimonials/natalia@2.png" width="64" alt="Natalia">
Назву класу пишемо через дефіс

Не підтягується зображення для щільності пікселів DPR: 1.0
Ви забули вказати дескриптор 2x в атрибуті srcset. В слак надам Вам скріншот, як це має виглядати

2023-10-01 21:12 UTC, VeronikaVaraksina1 commented on src/partials/testimonials.html
> +            <img class="image_icon" src="../img/testimonials/maria.png" srcset="../img/testimonials/maria@2.png" width="64" alt="Maria">
Назву класу пишемо через дефіс

Не підтягується зображення для щільності пікселів DPR: 1.0
Ви забули вказати дескриптор 2x в атрибуті srcset. В слак надам Вам скріншот, як це має виглядати

2023-10-02 16:08 UTC, GudvinPRO commented on src/css/testimonials.css
>  .staff-title {
Зробив

2023-10-02 16:11 UTC, GudvinPRO commented on src/partials/testimonials.html
>                  <p class="staff-paragraph">
зробив

2023-10-02 18:32 UTC, VeronikaVaraksina1 approved these changes

2023-10-02 18:33 UTC, merged